### ISSUE TITLE
Please add license

### ISSUE THREAD

**Issue by ChrisSandison** [jonathanhds/sql-builder#5]
I would be interested in using this work in a derivative product. As it stands right now, we are unable to since it is not licensed. Would you be open to putting an MIT license on this?

**Comment by llorllale** [comment]
@ChrisSandison can I interest you with [llorllale/sql4j](https://github.com/llorllale/sql4j)? It's licensed, but also inactive, but I'm willing to develop it further if there is any interest.

**Comment by snail007** [comment]
@ChrisSandison https://github.com/snail007/go-activerecord/tree/master/mysql
